### ISSUE TITLE
Using jupyter nbconvert to slides with IHaskell

### ISSUE THREAD

**Issue by skeydan** [tweag/HaskellR#290]
Hi,

I am looking for a nice way to present about HaskellR.
Normally I use R presentation for that, but that would require calling Haskell from R, not the other way round ;-)
Instead, given the possibility to create IHaskell notebooks, I thought I'd use jupyter nbconvert to do a dynamic presentation. However, while the command 

`stack --nix exec jupyter nbconvert IHaskell/examples/play.ipynb -- --to slides --post serve`

works fine, instead of dynamic slides a static html page gets rendered.

I see a reveal.js related error on the console, plus a SSL related stacktrace (not sure if one is the cause of the other):

ERROR:tornado.application:Uncaught exception GET /reveal.js/css/reveal.css (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/reveal.js/css/reveal.css', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'User-Agent': 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Referer': 'http://127.0.0.1:8000/play.slides.html', 'Cache-Control': 'max-age=0', 'Accept': 'text/css,*/*;q=0.1'})
Traceback (most recent call last):
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/nix/store/ml2vmsibrwkzqxfddlp2qfvanc36fxh5-python3.5-nbconvert-5.1.1/lib/python3.5/site-packages/nbconvert/postprocessors/serve.py", line 30, in finish_get
    response.rethrow()
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/httpclient.py", line 587, in rethrow
    raise self.error
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/gen.py", line 267, in <lambda>
    future, lambda future: callback(future.result()))
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/tcpclient.py", line 174, in connect
    server_hostname=host)
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/nix/store/3b7shwpvv1d94iax9qvcf9icmj01k3wg-python3.5-tornado-4.4.2/lib/python3.5/site-packages/tornado/iostream.py", line 1259, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/nix/store/zvm545rqc4d97caqq9h7344bnd06jhzb-python3-3.5.3/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/nix/store/zvm545rqc4d97caqq9h7344bnd06jhzb-python3-3.5.3/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()

For comparison, I've used jupyter nbconvert --to slides in a Python (Anaconda) environment, there it works well with the slides (and no reveal.js errors).

Would you happen to know what I can do to make this work?
Otherwise, would you have advice which technology to use when presenting about HaskellR?

Thank you so much in advance!!!

Best,
Sigrid

**Comment by skeydan** [comment]
It's really  a minor thing, I'll close it.

**Comment by Fuuzetsu** [comment]
Sorry, didn't see this issue before. Did you find a suitable alternative or you'd still like to get some help? I would be starting blind pretty much, I'm personally not R/jupyter user but two sets of eyes are always better than one.

**Comment by skeydan** [comment]
Hi, thanks for asking, I think I'll get along using R markdown for static presentation and Jupyter notebook (not slides) for a demo.
